name: empoderaadmin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
 
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_database: ^10.3.16

  # Gerenciamento de variÃ¡veis de ambiente
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
  # Pasta principal de assets
    - assets/

  fonts:
    - family: Crewniverse
      fonts:
        - asset: assets/fonts/crewniverse.otf 
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf